#!/usr/bin/env python3
"""Builds the pronunciation audio for the site (macOS only: uses `say` and `afconvert`).

1. Reads tools/.cache/texts.json (written by extract-audio-texts.js).
2. Records each text once with the French voice "Thomas" (cached by content hash).
3. Joins each group's clips into one sprite with silence between clips and encodes it as AAC in an .mp4 container (served by the Artifact viewer).
4. Writes src/24-audio-map.js: AUDIO_SPRITES (file names) and AUDIO_MAP (text -> [sprite, start ms, duration ms]).
"""
import hashlib
import json
import os
import subprocess
import sys
import tempfile
import wave
from concurrent.futures import ThreadPoolExecutor

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "tools", ".cache", "clips")
OUT_AUDIO = os.path.join(ROOT, "assets", "audio")
OUT_MAP = os.path.join(ROOT, "src", "24-audio-map.js")
VOICE = os.environ.get("VOICE", "Thomas")
RATE = os.environ.get("RATE", "165")
SAMPLE_RATE = 22050
PAD_MS = 350  # silence before and after every clip, so small seek errors never reach the next word

os.makedirs(CACHE, exist_ok=True)
os.makedirs(OUT_AUDIO, exist_ok=True)


def clip_path(text):
    h = hashlib.sha1(f"{VOICE}|{RATE}|{text}".encode("utf-8")).hexdigest()[:16]
    return os.path.join(CACHE, h + ".wav")


def record(text):
    out = clip_path(text)
    if os.path.exists(out) and os.path.getsize(out) > 100:
        return out
    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False, encoding="utf-8") as f:
        f.write(text)
        txt = f.name
    try:
        subprocess.run(["say", "-v", VOICE, "-r", RATE, "--file-format=WAVE",
                        f"--data-format=LEI16@{SAMPLE_RATE}", "-o", out, "-f", txt],
                       check=True, capture_output=True)
    finally:
        os.unlink(txt)
    return out


def main():
    data = json.load(open(os.path.join(ROOT, "tools", ".cache", "texts.json"), encoding="utf-8"))
    texts = [t for g in data["groups"] for t in g["texts"]]
    print(f"Recording {len(texts)} clips with voice {VOICE}…", file=sys.stderr)
    with ThreadPoolExecutor(max_workers=8) as pool:
        list(pool.map(record, texts))

    pad = b"\x00\x00" * int(SAMPLE_RATE * PAD_MS / 1000)
    sprites, amap = [], {}
    for gi, g in enumerate(data["groups"]):
        name = g["name"]
        sprites.append(name)
        frames = bytearray()
        for t in g["texts"]:
            with wave.open(clip_path(t), "rb") as w:
                assert w.getframerate() == SAMPLE_RATE and w.getsampwidth() == 2 and w.getnchannels() == 1
                pcm = w.readframes(w.getnframes())
            frames += pad
            start = len(frames) // 2
            frames += pcm
            amap[t] = [gi, round(start * 1000 / SAMPLE_RATE), round(len(pcm) // 2 * 1000 / SAMPLE_RATE)]
        frames += pad
        wav = os.path.join(tempfile.gettempdir(), f"ligne-b1-{name}.wav")
        with wave.open(wav, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(SAMPLE_RATE)
            w.writeframes(bytes(frames))
        out = os.path.join(OUT_AUDIO, name + ".mp4")
        subprocess.run(["afconvert", "-f", "m4af", "-d", "aac", "-b", "40000", wav, out], check=True)
        os.unlink(wav)
        print(f"  {name}.mp4  {len(g['texts'])} clips  {os.path.getsize(out) // 1024} KB", file=sys.stderr)

    with open(OUT_MAP, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/make-audio.py. Do not edit by hand. */\n")
        f.write(f"const AUDIO_VOICE = {json.dumps(VOICE)};\n")
        f.write("const AUDIO_SPRITES = " + json.dumps(sprites) + ";\n")
        f.write("const AUDIO_MAP = " + json.dumps(amap, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"Wrote {OUT_MAP}", file=sys.stderr)


if __name__ == "__main__":
    main()
