/* ============ Verbs + prepositions ============
   Constructions based on S. Auger & L. Pronovost, « Le verbe et ses prépositions », niveau avancé (UQTR, EIF).
   Entry: [verbe, español, "construction|construction", remarque?, exemple?, groupe?]
   groupe: v = verbe, e = locution avec être, a = locution avec avoir, i = expression impersonnelle */
const VERBS_RAW = [
  ["s'abstenir", "abstenerse", "de qqch|de faire qqch", "", "Elle s'est abstenue de parler toute la réunion."],
  ["accepter", "aceptar", "qqch|de faire qqch", "", "Il a accepté de nous aider."],
  ["acheter", "comprar", "qqch à qqn", "", "J'ai acheté un cadeau à ma sœur."],
  ["s'adapter", "adaptarse", "à qqch|à qqn", "", "Il faut s'adapter à la nouvelle culture."],
  ["adresser", "dirigir, enviar", "qqch à qqn"],
  ["s'adresser", "dirigirse a", "à qqn", "", "Adressez-vous à l'accueil."],
  ["aider", "ayudar", "qqn|qqn à faire qqch", "COD: je l'aide (no « je lui aide »).", "Cet enseignant aide Paul à écrire."],
  ["aimer", "gustar, amar", "qqch|qqn|faire qqch", "Sin preposición ante infinitivo.", "J'aime voyager."],
  ["aller", "ir (a hacer)", "faire qqch", "", "Je vais faire les courses."],
  ["s'amuser", "divertirse", "à qqch|à faire qqch", "", "Il s'amuse à raconter des histoires."],
  ["annoncer", "anunciar", "qqch à qqn"],
  ["apercevoir", "divisar, ver", "qqch|qqn"],
  ["s'apercevoir", "darse cuenta de", "de qqch", "", "Le patron s'est aperçu de ton absence."],
  ["appeler", "llamar", "qqn", "COD: je l'appelle.", "J'appellerai Caroline ce soir."],
  ["s'appliquer", "esmerarse, aplicarse", "à qqch|à faire qqch"],
  ["apporter", "traer", "qqch à qqn"],
  ["apprendre", "aprender / enseñar", "qqch à qqn|à qqn à faire qqch|de qqn à faire qqch", "… à l'élève (enseñar) · … du professeur (aprender de).", "J'apprends aux étudiants à parler français."],
  ["arrêter", "detener, dejar de", "qqch|qqn|de faire qqch", "", "Arrête de jouer, il est tard !"],
  ["s'arrêter", "pararse, dejar de", "de faire qqch"],
  ["attendre", "esperar", "qqch|qqn", "Sin preposición: j'attends le bus.", "J'attends le bus depuis vingt minutes."],
  ["s'attendre", "esperarse, prever", "à qqch|à faire qqch", "", "Je ne m'attendais pas à ce résultat."],
  ["avoir", "tener (que)", "qqch|qqn|à faire qqch", "", "J'ai un texte à rédiger."],
  ["blesser", "herir", "qqn"],
  ["brosser", "cepillar", "qqch de qqn"],
  ["cacher", "esconder, ocultar", "qqch à qqn", "Pero se dice « cacher qqn » (esconder a alguien)."],
  ["cesser", "cesar, dejar de", "qqch|de faire qqch", "", "Il a cessé de fumer."],
  ["chanter", "cantar", "qqch à qqn"],
  ["chercher", "buscar / intentar", "qqch|qqn|à faire qqch", "Chercher à = intentar.", "Il cherche à comprendre."],
  ["choisir", "elegir", "qqch|qqn|de faire qqch", "", "Vincent a choisi de terminer ses études en France."],
  ["commencer", "empezar", "qqch|à faire qqch", "", "Il commence à pleuvoir."],
  ["confirmer", "confirmar", "qqch à qqn"],
  ["conseiller", "aconsejar", "qqch à qqn|à qqn de faire qqch", "", "Je te conseille de partir tôt."],
  ["continuer", "continuar", "qqch|de faire qqch", "También « continuer à » en el uso corriente.", "Simon continue de pratiquer le karaté."],
  ["contribuer", "contribuir", "à faire qqch"],
  ["convaincre", "convencer", "qqn de faire qqch", "", "Elle m'a convaincu de venir."],
  ["craindre", "temer", "qqch|qqn|de faire qqch"],
  ["critiquer", "criticar", "qqch|qqn"],
  ["croire", "creer", "qqch|qqn|faire qqch", "Sin preposición ante infinitivo."],
  ["décider", "decidir", "qqch|de faire qqch|qqn à faire qqch", "Décider qqn à faire qqch = convencer a alguien.", "J'ai décidé de continuer."],
  ["se décider", "decidirse", "à faire qqch", "", "Je me suis décidée à prendre des cours."],
  ["demander", "pedir, preguntar", "qqch à qqn|à qqn de faire qqch", "Pero: je demande à faire qqch (pido permiso para hacer algo).", "Demande à Olivier de te conduire."],
  ["dépendre", "depender", "de qqch|de qqn", "", "Ça dépend de la météo."],
  ["désirer", "desear", "qqch|qqn|faire qqch"],
  ["détester", "detestar", "qqch|qqn|faire qqch"],
  ["devenir", "llegar a ser", "qqch|qqn"],
  ["devoir", "deber", "qqch à qqn|faire qqch", "", "Je dois partir."],
  ["dire", "decir", "qqch à qqn|à qqn de faire qqch", "", "Il m'a dit de ne pas m'inquiéter."],
  ["donner", "dar", "qqch à qqn|à faire qqch", "", "Le professeur nous a donné des devoirs à faire."],
  ["écrire", "escribir", "qqch à qqn"],
  ["écouter", "escuchar", "qqch|qqn|faire qqch", "COD: je l'écoute."],
  ["empêcher", "impedir", "qqch|qqn de faire qqch", "", "Le bruit m'empêche de dormir."],
  ["emprunter", "pedir prestado", "qqch à qqn", "", "J'ai emprunté un livre à Julie."],
  ["encourager", "animar, alentar", "qqn à faire qqch", "", "L'entraîneur encourage les athlètes à persévérer."],
  ["s'ennuyer", "aburrirse / extrañar", "de qqch|de qqn|de faire qqch", "S'ennuyer de qqn = echar de menos (uso de Quebec)."],
  ["enseigner", "enseñar", "qqch à qqn|à qqn à faire qqch"],
  ["entendre", "oír", "qqch|qqn|faire qqch"],
  ["entendre parler", "oír hablar", "de qqch|de qqn", "", "Tu as entendu parler de ce film ?"],
  ["envoyer", "enviar", "qqch à qqn"],
  ["espérer", "esperar (desear)", "qqch|qqch de qqn|faire qqch", "Sin preposición ante infinitivo.", "J'espère vous voir bientôt."],
  ["essayer", "intentar, probar", "qqch|de faire qqch", "", "Je vais essayer de parler à la directrice."],
  ["éviter", "evitar", "qqch|qqn|de faire qqch"],
  ["excuser", "disculpar", "qqch|qqn de faire qqch"],
  ["s'excuser", "disculparse", "de qqch|de faire qqch", "", "Il s'est excusé de son retard."],
  ["exiger", "exigir", "qqch de qqn|de faire qqch"],
  ["expliquer", "explicar", "qqch à qqn"],
  ["faire", "hacer", "qqch à qqn"],
  ["falloir", "hacer falta", "qqch|qqn|faire qqch", "Il faut qqn pour faire qqch."],
  ["se fatiguer", "cansarse", "de qqch|de qqn|de faire qqch"],
  ["féliciter", "felicitar", "qqn de qqch|qqn de faire qqch", "", "Je te félicite de ton succès."],
  ["se fier", "fiarse de", "à qqn", "Se fier à (¡no « de »!).", "Il se fie à mon bon goût."],
  ["finir", "terminar", "qqch|de faire qqch", "", "J'ai fini de travailler."],
  ["habituer", "acostumbrar", "qqn à faire qqch"],
  ["s'habituer", "acostumbrarse", "à qqch|à qqn|à faire qqch", "", "Je me suis habitué à la vie à Paris."],
  ["hésiter", "dudar, vacilar", "à faire qqch", "", "N'hésitez pas à me contacter."],
  ["interdire", "prohibir", "qqch à qqn|à qqn de faire qqch", "", "Il est interdit aux visiteurs de nourrir les animaux."],
  ["s'intéresser", "interesarse por", "à qqch|à qqn", "", "Elle s'intéresse à la littérature."],
  ["inviter", "invitar", "qqn à faire qqch", "", "Il nous invite à dîner."],
  ["jouer", "jugar / tocar", "à qqch|de qqch|à faire qqch", "Jouer à un sport o juego · jouer de un instrumento.", "Camille joue du violon, mais elle ne joue pas au tennis."],
  ["laisser", "dejar", "qqch à qqn|qqn faire qqch"],
  ["lire", "leer", "qqch à qqn"],
  ["louer", "alquilar", "qqch à qqn"],
  ["manquer", "perder / faltar / echar de menos", "qqch|de qqch|qqn|à qqn|de faire qqch", "Manquer de = carecer · manquer à = sentimientos (Tu me manques = te echo de menos).", "Tu me manques beaucoup."],
  ["se méfier", "desconfiar", "de qqch|de qqn", "", "Il faut se méfier des fraudeurs."],
  ["menacer", "amenazar", "qqn de faire qqch"],
  ["mériter", "merecer", "qqch|de faire qqch"],
  ["mettre du temps", "tardar en", "à faire qqch", "", "Il met beaucoup de temps à répondre."],
  ["se mettre", "ponerse a", "à qqch|à faire qqch", "", "Elles se sont mises à chanter."],
  ["montrer", "mostrar", "qqch à qqn"],
  ["négliger", "descuidar", "qqch|qqn|de faire qqch"],
  ["obliger", "obligar", "qqn à faire qqch", "", "On m'a obligé à signer."],
  ["obtenir", "obtener", "qqch de qqn"],
  ["s'occuper", "ocuparse de, cuidar", "de qqch|de qqn|de faire qqch", "", "Je m'occupe des enfants."],
  ["offrir", "regalar, ofrecer", "qqch à qqn|à qqn de faire qqch"],
  ["s'opposer", "oponerse", "à qqch|à qqn"],
  ["oser", "atreverse", "qqch|faire qqch", "Sin preposición: on ose faire qqch.", "Je n'ose pas lui dire."],
  ["oublier", "olvidar", "qqch|qqn|de faire qqch", "", "J'ai oublié de fermer la porte."],
  ["parler", "hablar", "de qqch à qqn|de qqn|de faire qqch", "Parler à qqn (con alguien) · parler de qqn (de alguien ausente).", "Je vais parler à la directrice du nouvel horaire."],
  ["pardonner", "perdonar", "qqch à qqn", "COI: je lui pardonne."],
  ["passer", "pasar", "qqch à qqn|faire qqch", "", "Passe-moi le sel. / Je passerai te voir."],
  ["payer", "pagar", "qqch|qqn", "Pero: payer qqch à qqn."],
  ["penser", "pensar", "à qqch|qqch|à qqn|de qqn|à faire qqch", "Penser de = opinión (Qu'est-ce que tu penses de ce film ?) · penser à = tener en mente.", "Pense à acheter du pain !"],
  ["perdre", "perder", "qqch|qqn"],
  ["perdre du temps", "perder el tiempo", "à qqch|avec qqn|à faire qqch"],
  ["permettre", "permitir", "qqch à qqn|à qqn de faire qqch", "", "Ce diplôme me permet de travailler."],
  ["persuader", "persuadir", "qqn de faire qqch"],
  ["se plaindre", "quejarse", "de qqch|de qqn|de faire qqch", "", "Il se plaint toujours du bruit."],
  ["porter", "llevar", "qqch|qqn"],
  ["pouvoir", "poder", "faire qqch"],
  ["préférer", "preferir", "qqch|qqn|faire qqch", "Sin preposición ante infinitivo.", "Je préfère rester ici."],
  ["prendre", "tomar", "qqch|qqn"],
  ["prendre plaisir", "disfrutar", "à faire qqch"],
  ["prendre soin", "cuidar", "de qqch|de qqn|de faire qqch", "", "Daniel prend soin de son père."],
  ["se préparer", "prepararse", "à qqch|à faire qqch"],
  ["présenter", "presentar", "qqch à qqn"],
  ["promettre", "prometer", "qqch à qqn|à qqn de faire qqch", "", "Je te promets de revenir."],
  ["proposer", "proponer", "qqch à qqn|qqn|à qqn de faire qqch", "Proposer qqn = sugerir a alguien (como candidato)."],
  ["raconter", "contar", "qqch à qqn"],
  ["rappeler", "recordar (a alguien)", "qqch à qqn", "", "Rappelle-moi ton numéro."],
  ["se rappeler", "acordarse", "qqch|qqn|faire qqch", "Sin « de »: je me rappelle nos vacances.", "Je me rappelle nos dernières vacances."],
  ["recevoir", "recibir", "qqch de qqn|qqn", "Recevoir qqn = invitar, acoger."],
  ["recommander", "recomendar", "qqch à qqn|qqn|à qqn de faire qqch"],
  ["réfléchir", "reflexionar", "à qqch", "", "Il est bon de réfléchir à la question."],
  ["refuser", "negarse, rechazar", "qqch à qqn|de faire qqch", "", "Il refuse de répondre."],
  ["regarder", "mirar", "qqch|qqn|faire qqch"],
  ["regretter", "lamentar, echar de menos", "qqch|qqn|de faire qqch", "", "Il regrette d'avoir oublié ton anniversaire."],
  ["remercier", "agradecer", "qqn de faire qqch", "COD: je la remercie.", "Merci de nous avoir reçus."],
  ["remettre", "entregar", "qqch à qqn"],
  ["rencontrer", "encontrar, conocer", "qqch|qqn"],
  ["renoncer", "renunciar", "à qqch|à qqn|à faire qqch"],
  ["répondre", "responder", "qqch|à qqch|à qqn", "Répondre à une question.", "Le patron a répondu aux questions du journaliste."],
  ["ressembler", "parecerse", "à qqch|à qqn", "", "Il ressemble à son père."],
  ["réussir", "lograr, aprobar", "qqch|à faire qqch", "Pero: qqch réussit à qqn (algo le sale bien).", "J'ai réussi à passer l'examen."],
  ["rêver", "soñar", "de qqch|de qqn|de faire qqch|à qqch|à qqn", "Rêver de = soñar con (dormido o como deseo) · rêver à = pensar vagamente en.", "Sophie rêve de partir au soleil."],
  ["rire", "reírse", "de qqch|de qqn"],
  ["risquer", "arriesgar", "qqch|de faire qqch", "", "Tu risques de perdre ton argent."],
  ["savoir", "saber", "qqch|faire qqch", "", "Je sais nager."],
  ["servir", "servir", "qqch|à qqch|qqn|à qqn|à faire qqch", "Pero: qqn sert de guide (hace de guía).", "Ce crayon sert à écrire sur le tissu."],
  ["se servir", "usar, servirse", "de qqch|de qqn", "", "Je me sers de mon téléphone comme réveil."],
  ["songer", "pensar en", "à qqch|à qqn|à faire qqch"],
  ["souhaiter", "desear", "qqch à qqn|de faire qqch", "", "Je te souhaite bonne chance."],
  ["se souvenir", "acordarse de", "de qqch|de qqn|de faire qqch", "Con « de » (a diferencia de se rappeler).", "Je me souviens de notre voyage."],
  ["suggérer", "sugerir", "qqch à qqn|à qqn de faire qqch"],
  ["téléphoner", "llamar por teléfono", "à qqn", "COI: je lui téléphone.", "Il téléphone à Alexandra tous les mois."],
  ["tenir", "sostener / apreciar", "qqch|à qqch|qqn|à qqn|à faire qqch", "Tenir à = apreciar mucho / insistir en.", "Je tiens à te remercier."],
  ["tenter", "intentar", "qqch|de faire qqch"],
  ["trouver", "encontrar", "qqch|qqn"],
  ["utiliser", "utilizar", "qqch|qqn|pour faire qqch"],
  ["venir", "venir", "chez qqn|faire qqch", "", "Viens dîner chez nous !"],
  ["visiter", "visitar (un lugar)", "qqch|qqn", "En Francia: visiter un lieu, pero rendre visite à qqn."],
  ["vouloir", "querer", "qqch|qqn|faire qqch"],
  /* être */
  ["être censé", "se supone que", "faire qqch", "", "", "e"],
  ["être content", "estar contento", "de qqch|de qqn|de faire qqch", "", "Je suis content de te voir.", "e"],
  ["être disposé", "estar dispuesto", "à faire qqch", "", "", "e"],
  ["être fier", "estar orgulloso", "de qqch|de qqn|de faire qqch", "", "", "e"],
  ["être (mal)heureux", "estar feliz / triste", "de qqch|de faire qqch", "", "", "e"],
  ["être obligé", "estar obligado", "de faire qqch", "", "Je suis obligé de partir.", "e"],
  ["être prêt", "estar listo", "à faire qqch", "", "Je suis prêt à partir.", "e"],
  ["être satisfait", "estar satisfecho", "de qqch|de qqn", "", "", "e"],
  /* avoir */
  ["avoir besoin", "necesitar", "de qqch|de qqn|de faire qqch", "", "J'ai besoin de repos.", "a"],
  ["avoir envie", "tener ganas", "de qqch|de qqn|de faire qqch", "", "J'ai envie de faire du sport.", "a"],
  ["avoir hâte", "tener muchas ganas", "de faire qqch", "", "J'ai hâte de te revoir.", "a"],
  ["avoir honte", "avergonzarse", "de qqch|de qqn|de faire qqch", "", "", "a"],
  ["avoir la chance", "tener la suerte", "de faire qqch", "", "", "a"],
  ["avoir l'air", "parecer", "de qqch|de qqn|de faire qqch", "", "Tu as l'air fatigué.", "a"],
  ["avoir l'habitude", "estar acostumbrado", "de qqch|de qqn|de faire qqch", "", "J'ai l'habitude de manger tôt.", "a"],
  ["avoir l'intention", "tener la intención", "de faire qqch", "", "", "a"],
  ["avoir l'occasion", "tener la ocasión", "de faire qqch", "", "", "a"],
  ["avoir le temps", "tener tiempo", "de faire qqch", "", "Je n'ai pas eu le temps de répondre.", "a"],
  ["avoir mal", "dolerle a uno", "à qqch", "", "J'ai mal à la tête.", "a"],
  ["avoir peur", "tener miedo", "de qqch|de qqn|de faire qqch", "", "Il a peur du noir.", "a"],
  ["avoir raison", "tener razón", "de qqch|de faire qqch", "", "", "a"],
  ["avoir soin", "cuidar", "de qqch|de qqn|de faire qqch", "", "", "a"],
  ["avoir tort", "equivocarse", "de faire qqch", "", "Tu as tort de t'inquiéter.", "a"],
  /* impersonnelles */
  ["ce n'est pas la peine", "no vale la pena", "de faire qqch", "", "Ce n'est pas la peine de me le répéter.", "i"],
  ["il est bon", "es bueno", "de faire qqch", "", "", "i"],
  ["il est important", "es importante", "de faire qqch", "", "", "i"],
  ["il est temps", "ya es hora", "de faire qqch", "", "Il est temps de rentrer.", "i"],
  ["il faut", "hace falta, hay que", "qqch|qqn|faire qqch", "Pero: il faut qqn pour faire qqch.", "Il faut travailler pour réussir.", "i"],
  ["il s'agit", "se trata", "de qqch|de qqn|de faire qqch", "", "Il s'agit d'apprendre à danser.", "i"],
  ["il vaut mieux", "más vale", "faire qqch", "", "Il vaut mieux finir aujourd'hui.", "i"]
];

/* French versions of the remarks (the Spanish ones live in VERBS_RAW) */
const VERB_RM_FR = {
  "aider": "COD : je l'aide (pas « je lui aide »).",
  "aimer": "Sans préposition devant l'infinitif.",
  "appeler": "COD : je l'appelle.",
  "apprendre": "… à l'élève (enseigner) · … du professeur (apprendre de quelqu'un).",
  "attendre": "Sans préposition : j'attends le bus.",
  "cacher": "Mais on dit aussi « cacher qqn ».",
  "chercher": "Chercher à = essayer de.",
  "continuer": "« Continuer à » est aussi courant.",
  "croire": "Sans préposition devant l'infinitif.",
  "décider": "Décider qqn à faire qqch = le convaincre.",
  "demander": "Mais : je demande à faire qqch (demander la permission).",
  "écouter": "COD : je l'écoute.",
  "s'ennuyer": "S'ennuyer de qqn = regretter son absence (usage québécois).",
  "espérer": "Sans préposition devant l'infinitif.",
  "falloir": "Il faut qqn pour faire qqch.",
  "se fier": "Se fier à (pas « de » !).",
  "jouer": "Jouer à un sport ou à un jeu · jouer d'un instrument.",
  "manquer": "Manquer de = ne pas avoir assez · manquer à = sentiments (Tu me manques).",
  "oser": "Sans préposition : on ose faire qqch.",
  "parler": "Parler à qqn (s'adresser à lui) · parler de qqn (d'une personne absente).",
  "pardonner": "COI : je lui pardonne.",
  "payer": "Mais : payer qqch à qqn.",
  "penser": "Penser de = opinion (Qu'est-ce que tu penses de ce film ?) · penser à = avoir en tête.",
  "préférer": "Sans préposition devant l'infinitif.",
  "proposer": "Proposer qqn = suggérer quelqu'un (comme candidat).",
  "se rappeler": "Sans « de » : je me rappelle nos vacances.",
  "recevoir": "Recevoir qqn = inviter, accueillir.",
  "remercier": "COD : je la remercie.",
  "répondre": "Répondre à une question.",
  "réussir": "Mais : qqch réussit à qqn (lui est favorable).",
  "rêver": "Rêver de = voir en rêve ou désirer · rêver à = penser vaguement à.",
  "servir": "Mais : qqn sert de guide (joue le rôle de guide).",
  "se souvenir": "Avec « de » (contrairement à se rappeler).",
  "téléphoner": "COI : je lui téléphone.",
  "tenir": "Tenir à = être attaché à / insister pour.",
  "visiter": "En France : visiter un lieu, mais rendre visite à qqn.",
  "il faut": "Mais : il faut qqn pour faire qqch."
};

const VERBS = VERBS_RAW.map(function (r) {
  const cons = r[2].split("|");
  const cats = new Set();
  cons.forEach(function (c) {
    if (/^à faire/.test(c) || / à faire/.test(c)) cats.add("a-inf");
    if (/^de faire/.test(c) || / de faire/.test(c)) cats.add("de-inf");
    if (/^faire qqch$/.test(c) || /qqn faire qqch/.test(c)) cats.add("x-inf");
    if (/à qqn/.test(c)) cats.add("a-qqn");
    if (/^de qq/.test(c) || / de qq(n|ch)$/.test(c)) cats.add("de-qq");
  });
  const g = r[5] || "v";
  if (g !== "v") cats.add("loc");
  const rm = r[3] ? bi(r[3], VERB_RM_FR[r[0]] || r[3]) : "";
  return { v: r[0], es: r[1], cons: cons, rm: rm, ex: r[4] || "", g: g, cats: cats };
});

const VERB_FILTERS = [
  ["all", bi("Todos", "Tous")], ["a-inf", bi("à + infinitivo", "à + infinitif")], ["de-inf", bi("de + infinitivo", "de + infinitif")], ["x-inf", bi("infinitivo directo", "infinitif direct")], ["a-qqn", bi("à + persona", "à + personne")], ["de-qq", bi("de + algo/alguien", "de + qqch/qqn")], ["loc", bi("Locuciones être / avoir / il", "Locutions être / avoir / il")]
];

const VERB_CONTRASTS = [
  ["penser à / penser de", bi("<i>Je pense à toi</i> (pienso en ti) · <i>Que penses-tu de ce film ?</i> (¿qué opinas de…?)", "<i>Je pense à toi</i> (tu es dans ma tête) · <i>Que penses-tu de ce film ?</i> (ton opinion)")],
  ["manquer à / manquer de", bi("<i>Tu me manques</i> (te echo de menos: ¡sujeto invertido!) · <i>Il manque de patience</i> (le falta paciencia).", "<i>Tu me manques</i> (le sujet est la personne absente !) · <i>Il manque de patience</i> (il n'en a pas assez).")],
  ["jouer à / jouer de", bi("<i>jouer au tennis</i> (deporte, juego) · <i>jouer du piano</i> (instrumento).", "<i>jouer au tennis</i> (sport, jeu) · <i>jouer du piano</i> (instrument).")],
  ["se rappeler / se souvenir de", bi("<i>Je me rappelle ce jour</i> · <i>Je me souviens de ce jour</i>.", "<i>Je me rappelle ce jour</i> · <i>Je me souviens de ce jour</i>.")],
  ["demander à qqn de faire", bi("<i>Je demande à Paul de venir</i> (pido a Paul que venga) · <i>Je demande à partir</i> (pido permiso para irme).", "<i>Je demande à Paul de venir</i> (Paul doit venir) · <i>Je demande à partir</i> (je demande la permission).")],
  ["parler à / parler de", bi("<i>Je parle à Julie</i> (con Julie) · <i>Je parle de Julie</i> (sobre Julie).", "<i>Je parle à Julie</i> (elle m'écoute) · <i>Je parle de Julie</i> (elle est le sujet).")],
  ["servir à / servir de", bi("<i>Ce crayon sert à écrire</i> (sirve para) · <i>Il sert de guide</i> (hace de guía).", "<i>Ce crayon sert à écrire</i> (usage) · <i>Il sert de guide</i> (rôle).")],
  [bi("COD o COI", "COD ou COI"), bi("Sin preposición en francés: <i>aider, appeler, attendre, écouter, remercier qqn</i>. Con <i>à</i>: <i>téléphoner, répondre, ressembler, pardonner, obéir à qqn</i>.", "Sans préposition : <i>aider, appeler, attendre, écouter, remercier qqn</i>. Avec <i>à</i> : <i>téléphoner, répondre, ressembler, pardonner, obéir à qqn</i>.")]
];

/* Normalised text used both as the audio-clip key and for speech synthesis */
function speakText(t) {
  return String(t).replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&nbsp;/g, " ")
    .replace(/\([^)]*\)/g, "").replace(/qqch/g, "quelque chose").replace(/qqn/g, "quelqu'un")
    .replace(/\s*→\s*/g, ", ").replace(/\s\/\s/g, ", ").replace(/[«»‿]/g, "")
    .replace(/\s+/g, " ").replace(/\s+([,.;:!?])/g, "$1").trim();
}
